service: sls-docker-python

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

package:
  exclude:
    - node_modules/**
    - .git/**
    - venv/**
    - "*.md"
    - Dockerfile
    - ".dockerignore"
    - "*/.ipynb_checkpoints/*"

plugins:
  - serverless-offline-python
#  - serverless-python-requirements
#  - serverless-dotenv-plugin

serverless-offline:
  host: 0.0.0.0
  port: 3000
  httpPort: 3000
  resourceRoutes: true
